name: Test Fantasy Report

on:
  workflow_dispatch: # manual trigger

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install espn-api pandas

      - name: Run score tracker twice with 15s pause
        run: |
          python score_tracker.py
          sleep 15
          python score_tracker.py

      - name: Upload scores.csv
        uses: actions/upload-artifact@v3
        with:
          name: scores
          path: scores.csv
